/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bmstu.geofence.manager.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Geozone service. Represents a row in the &quot;GM_Geozone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bmstu.geofence.manager.core.model.impl.GeozoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bmstu.geofence.manager.core.model.impl.GeozoneImpl}.
 * </p>
 *
 * @author Ershov
 * @see Geozone
 * @see com.bmstu.geofence.manager.core.model.impl.GeozoneImpl
 * @see com.bmstu.geofence.manager.core.model.impl.GeozoneModelImpl
 * @generated
 */
@ProviderType
public interface GeozoneModel extends BaseModel<Geozone>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a geozone model instance should use the {@link Geozone} interface instead.
	 */

	/**
	 * Returns the primary key of this geozone.
	 *
	 * @return the primary key of this geozone
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this geozone.
	 *
	 * @param primaryKey the primary key of this geozone
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this geozone.
	 *
	 * @return the uuid of this geozone
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this geozone.
	 *
	 * @param uuid the uuid of this geozone
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the geozone ID of this geozone.
	 *
	 * @return the geozone ID of this geozone
	 */
	public long getGeozoneId();

	/**
	 * Sets the geozone ID of this geozone.
	 *
	 * @param geozoneId the geozone ID of this geozone
	 */
	public void setGeozoneId(long geozoneId);

	/**
	 * Returns the group ID of this geozone.
	 *
	 * @return the group ID of this geozone
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this geozone.
	 *
	 * @param groupId the group ID of this geozone
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this geozone.
	 *
	 * @return the company ID of this geozone
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this geozone.
	 *
	 * @param companyId the company ID of this geozone
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this geozone.
	 *
	 * @return the user ID of this geozone
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this geozone.
	 *
	 * @param userId the user ID of this geozone
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this geozone.
	 *
	 * @return the user uuid of this geozone
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this geozone.
	 *
	 * @param userUuid the user uuid of this geozone
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this geozone.
	 *
	 * @return the user name of this geozone
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this geozone.
	 *
	 * @param userName the user name of this geozone
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this geozone.
	 *
	 * @return the create date of this geozone
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this geozone.
	 *
	 * @param createDate the create date of this geozone
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this geozone.
	 *
	 * @return the modified date of this geozone
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this geozone.
	 *
	 * @param modifiedDate the modified date of this geozone
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this geozone.
	 *
	 * @return the status of this geozone
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this geozone.
	 *
	 * @param status the status of this geozone
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this geozone.
	 *
	 * @return the status by user ID of this geozone
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this geozone.
	 *
	 * @param statusByUserId the status by user ID of this geozone
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this geozone.
	 *
	 * @return the status by user uuid of this geozone
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this geozone.
	 *
	 * @param statusByUserUuid the status by user uuid of this geozone
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this geozone.
	 *
	 * @return the status by user name of this geozone
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this geozone.
	 *
	 * @param statusByUserName the status by user name of this geozone
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this geozone.
	 *
	 * @return the status date of this geozone
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this geozone.
	 *
	 * @param statusDate the status date of this geozone
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this geozone.
	 *
	 * @return the name of this geozone
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this geozone.
	 *
	 * @param name the name of this geozone
	 */
	public void setName(String name);

	/**
	 * Returns the area of this geozone.
	 *
	 * @return the area of this geozone
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this geozone.
	 *
	 * @param area the area of this geozone
	 */
	public void setArea(String area);

	/**
	 * Returns the calendar ID of this geozone.
	 *
	 * @return the calendar ID of this geozone
	 */
	public long getCalendarId();

	/**
	 * Sets the calendar ID of this geozone.
	 *
	 * @param calendarId the calendar ID of this geozone
	 */
	public void setCalendarId(long calendarId);

	/**
	 * Returns the description of this geozone.
	 *
	 * @return the description of this geozone
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this geozone.
	 *
	 * @param description the description of this geozone
	 */
	public void setDescription(String description);

	/**
	 * Returns the geozone attributes of this geozone.
	 *
	 * @return the geozone attributes of this geozone
	 */
	@AutoEscape
	public String getGeozoneAttributes();

	/**
	 * Sets the geozone attributes of this geozone.
	 *
	 * @param geozoneAttributes the geozone attributes of this geozone
	 */
	public void setGeozoneAttributes(String geozoneAttributes);

	/**
	 * Returns <code>true</code> if this geozone is approved.
	 *
	 * @return <code>true</code> if this geozone is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this geozone is denied.
	 *
	 * @return <code>true</code> if this geozone is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this geozone is a draft.
	 *
	 * @return <code>true</code> if this geozone is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this geozone is expired.
	 *
	 * @return <code>true</code> if this geozone is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this geozone is inactive.
	 *
	 * @return <code>true</code> if this geozone is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this geozone is incomplete.
	 *
	 * @return <code>true</code> if this geozone is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this geozone is pending.
	 *
	 * @return <code>true</code> if this geozone is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this geozone is scheduled.
	 *
	 * @return <code>true</code> if this geozone is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Geozone geozone);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Geozone> toCacheModel();

	@Override
	public Geozone toEscapedModel();

	@Override
	public Geozone toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}